# Use an official Node.js image as the base image
FROM node:20.10.0

# Set the working directory inside the container
WORKDIR /src

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install --force

# Copy the rest of the application code to the container
COPY . .

# Run the patch-package command if needed
# RUN npm run patch-package

# Expose the port that the webpack server will run on
EXPOSE 9000

# Set the command to start the webpack server
CMD ["npm", "run", "dev"]