# Use an official Node.js image as the base image
FROM node:16.13.1

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies, including native modules like bcrypt
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Ensure the config file is correctly copied
COPY config/config.json ./src/database/config/config.json

# Expose the port that the server will run on
EXPOSE 9000

# Set the command to start the server
CMD ["npm", "run", "dev"]